version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trainer-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - trainer-network

networks:
  trainer-network:
    external: true